export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  COACH = 'COACH',
  ASSISTANT_COACH = 'ASSISTANT_COACH',
  GOALKEEPER = 'GOALKEEPER',
  PARENT = 'PARENT',
  READONLY = 'READONLY',
}
