import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1775784489468 implements MigrationInterface {
    name = 'InitSchema1775784489468'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "pgcrypto"`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_plan_enum" AS ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TYPE "public"."tenants_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "name" character varying(150) NOT NULL, "slug" character varying(150) NOT NULL, "plan" "public"."tenants_plan_enum" NOT NULL DEFAULT 'FREE', "status" "public"."tenants_status_enum" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2310ecc5cb8be427097154b18fc" UNIQUE ("slug"), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('SUPER_ADMIN', 'USER')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "fullName" character varying(150) NOT NULL, "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "role" "public"."users_role_enum" NOT NULL, "status" "public"."users_status_enum" NOT NULL DEFAULT 'ACTIVE', "emailVerifiedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "name" character varying(150) NOT NULL, "category" character varying(100), "season" character varying(100), "coachId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."training_sessions_status_enum" AS ENUM('DRAFT', 'PLANNED', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "training_sessions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "createdByUserId" uuid NOT NULL, "title" character varying(180) NOT NULL, "trainingContentIds" uuid array NOT NULL DEFAULT '{}', "description" text, "date" date NOT NULL, "startTime" TIMESTAMP WITH TIME ZONE NOT NULL, "endTime" TIMESTAMP WITH TIME ZONE NOT NULL, "teamId" uuid, "location" character varying(150), "notes" text, "status" "public"."training_sessions_status_enum" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6678399f77ed9db5176459befa9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "training_lines" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "name" character varying(150) NOT NULL, "description" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_112e53539768e9ff9c33ce7ccb6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "training_contents" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "trainingLineId" uuid NOT NULL, "name" character varying(180) NOT NULL, "description" text, "createdBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_347a0bb52dde7c5a213a60ba844" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_plan_enum" AS ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "plan" "public"."subscriptions_plan_enum" NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'TRIALING', "currentPeriodStart" TIMESTAMP WITH TIME ZONE NOT NULL, "currentPeriodEnd" TIMESTAMP WITH TIME ZONE NOT NULL, "trialEndsAt" TIMESTAMP WITH TIME ZONE, "canceledAt" TIMESTAMP WITH TIME ZONE, "cancelAtPeriodEnd" boolean NOT NULL DEFAULT false, "stripeCustomerId" character varying(200), "stripeSubscriptionId" character varying(200), "stripeSubscriptionItemId" character varying(200), "stripePriceId" character varying(200), "stripeScheduleId" character varying(200), "externalRef" character varying(200), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."plan_change_requests_requestedplan_enum" AS ENUM('FREE', 'BASIC', 'PRO', 'ENTERPRISE')`);
        await queryRunner.query(`CREATE TYPE "public"."plan_change_requests_paymentmethod_enum" AS ENUM('CARD', 'SPEI')`);
        await queryRunner.query(`CREATE TYPE "public"."plan_change_requests_status_enum" AS ENUM('PENDING_PAYMENT', 'PENDING_REVIEW', 'COMPLETED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "plan_change_requests" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "requestedByUserId" uuid, "requestedPlan" "public"."plan_change_requests_requestedplan_enum" NOT NULL, "paymentMethod" "public"."plan_change_requests_paymentmethod_enum" NOT NULL, "status" "public"."plan_change_requests_status_enum" NOT NULL DEFAULT 'PENDING_PAYMENT', "stripeCheckoutSessionId" character varying(200), "stripePaymentIntentId" character varying(200), "reviewedByUserId" uuid, "reviewedAt" TIMESTAMP WITH TIME ZONE, "reviewNotes" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8aca0e76d06e7339b0203bf0616" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "exercises" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "trainingContentId" uuid NOT NULL, "name" character varying(180) NOT NULL, "description" text, "instructions" text, "objective" text, "durationMinutes" integer, "repetitions" integer, "restSeconds" integer, "equipment" text, "videoUrl" character varying(500), "difficulty" character varying(50), "tacticalState" jsonb, "tacticalStateVersion" integer DEFAULT '1', "tacticalPreviewUrl" character varying(500), "tacticalHash" character varying(64), "tacticalUpdatedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c4c46f5fa89a58ba7c2d894e3c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session_contents" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "sessionId" uuid NOT NULL, "trainingContentId" uuid, "taskName" character varying(150) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_75163cf7eb55cf1d2fed4654e0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session_exercises" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "sessionId" uuid NOT NULL, "sessionContentId" uuid NOT NULL, "exerciseId" uuid NOT NULL, "selected" boolean NOT NULL DEFAULT true, "tacticalStateSnapshot" jsonb, "tacticalPreviewUrlSnapshot" character varying(500), "tacticalSnapshotCreatedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_307632aa851465406f972ef5866" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "goalkeeper_profiles" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "userId" uuid NOT NULL, "name" character varying(120), "dateOfBirth" date, "dominantHand" character varying(50), "dominantFoot" character varying(50), "height" numeric(5,2), "weight" numeric(5,2), "category" character varying(100), "teamId" uuid, "medicalNotes" text, "parentContact" character varying(255), "avatarUrl" character varying(500), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3362b295bc3988ff35668ffe2fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evaluation_items" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "evaluationId" uuid NOT NULL, "criterionCode" character varying(80) NOT NULL, "criterionLabel" character varying(160) NOT NULL, "score" integer NOT NULL, "comment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d76a05fd326065ae4a8215179f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evaluations" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "goalkeeperId" uuid NOT NULL, "trainingSessionId" uuid, "evaluatedByUserId" uuid NOT NULL, "evaluationDate" date NOT NULL, "overallScore" numeric(5,2) NOT NULL, "generalComment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f683b433eba0e6dae7e19b29e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LATE', 'JUSTIFIED')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "tenantId" uuid NOT NULL, "trainingSessionId" uuid NOT NULL, "goalkeeperId" uuid NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL DEFAULT 'PRESENT', "notes" text, "recordedByUserId" uuid, "recordedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_attendance_records_tenant_session_goalkeeper" UNIQUE ("tenantId", "trainingSessionId", "goalkeeperId"), CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."email_action_tokens_type_enum" AS ENUM('VERIFY_EMAIL', 'RESET_PASSWORD')`);
        await queryRunner.query(`CREATE TABLE "email_action_tokens" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "userId" uuid NOT NULL, "type" "public"."email_action_tokens_type_enum" NOT NULL, "tokenHash" character varying(128) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "consumedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0077ef721fc707af250eba976b6" UNIQUE ("tokenHash"), CONSTRAINT "PK_b2ca0a800c556521c374f5a9a8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6eb339774bf35477359d197a20" ON "email_action_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a09e89678290f14d7008d69018" ON "email_action_tokens" ("type") `);
        await queryRunner.query(`CREATE TABLE "auth_sessions" ("id" uuid NOT NULL, "userId" uuid NOT NULL, "refreshTokenHash" character varying(255) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_641507381f32580e8479efc36cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_c58f7e88c286e5e3478960a998b" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_e70292ca0e2e6126aa4f09a42d5" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_3d79526cc468e2156893fdb523a" FOREIGN KEY ("coachId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ADD CONSTRAINT "FK_9ff1ffdf267ca7e1a05761e967d" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ADD CONSTRAINT "FK_0cc76cb9b353d25e6521f747fd3" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_lines" ADD CONSTRAINT "FK_878e1351989f4a7b8ff96463b8d" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_contents" ADD CONSTRAINT "FK_f87d75feb9e02b9c11f7ca7b4af" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_contents" ADD CONSTRAINT "FK_24098a50e31457db8864073cf4a" FOREIGN KEY ("trainingLineId") REFERENCES "training_lines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_contents" ADD CONSTRAINT "FK_f88c40ed2328c7aba3afff8ffd5" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_0c5fe8e5f9f4dd4a8c0134abc9c" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_70e7e807de7b0f97a6053343bc9" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_89e03331414acea30470b8552fd" FOREIGN KEY ("trainingContentId") REFERENCES "training_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_contents" ADD CONSTRAINT "FK_d43e9d6405dc0909e7da4047b56" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_contents" ADD CONSTRAINT "FK_aa9929921831b3c67fa462069c3" FOREIGN KEY ("sessionId") REFERENCES "training_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_exercises" ADD CONSTRAINT "FK_adb01913c15e1236a8162d7402a" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_exercises" ADD CONSTRAINT "FK_ac33458407f217148bebb9d5d32" FOREIGN KEY ("sessionId") REFERENCES "training_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_exercises" ADD CONSTRAINT "FK_834fda65cf08684581b8ae46a74" FOREIGN KEY ("sessionContentId") REFERENCES "session_contents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session_exercises" ADD CONSTRAINT "FK_4a44dbff3e955c44d1f6e5d0796" FOREIGN KEY ("exerciseId") REFERENCES "exercises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goalkeeper_profiles" ADD CONSTRAINT "FK_7d3a6f8bb72b65dddef605cbfe1" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "goalkeeper_profiles" ADD CONSTRAINT "FK_65e8a99e66a68e0a6fad3f4e19d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluation_items" ADD CONSTRAINT "FK_9ac5a43efd1509a33fd824b3586" FOREIGN KEY ("evaluationId") REFERENCES "evaluations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_c6cb9662b64390a82abf1fa1b48" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_693d3ba3a3f768e31e8dd785b36" FOREIGN KEY ("goalkeeperId") REFERENCES "goalkeeper_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_5b27daf5679f5a886efa0ec3a53" FOREIGN KEY ("trainingSessionId") REFERENCES "training_sessions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_dbff782e38e228c797d8cf0eb81" FOREIGN KEY ("evaluatedByUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_94d977ec9616f19e799c7d7f8cd" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_3169ddfae2e6d56bb0ed7b6cd1c" FOREIGN KEY ("trainingSessionId") REFERENCES "training_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_ed3f3e286abf0b50f0d4b619f42" FOREIGN KEY ("goalkeeperId") REFERENCES "goalkeeper_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_7abef4618400ba2df0eb063b619" FOREIGN KEY ("recordedByUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_action_tokens" ADD CONSTRAINT "FK_6eb339774bf35477359d197a207" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "auth_sessions" ADD CONSTRAINT "FK_925b24d7fc2f9324ce972aee025" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "auth_sessions" DROP CONSTRAINT "FK_925b24d7fc2f9324ce972aee025"`);
        await queryRunner.query(`ALTER TABLE "email_action_tokens" DROP CONSTRAINT "FK_6eb339774bf35477359d197a207"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_7abef4618400ba2df0eb063b619"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_ed3f3e286abf0b50f0d4b619f42"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_3169ddfae2e6d56bb0ed7b6cd1c"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_94d977ec9616f19e799c7d7f8cd"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_dbff782e38e228c797d8cf0eb81"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_5b27daf5679f5a886efa0ec3a53"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_693d3ba3a3f768e31e8dd785b36"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_c6cb9662b64390a82abf1fa1b48"`);
        await queryRunner.query(`ALTER TABLE "evaluation_items" DROP CONSTRAINT "FK_9ac5a43efd1509a33fd824b3586"`);
        await queryRunner.query(`ALTER TABLE "goalkeeper_profiles" DROP CONSTRAINT "FK_65e8a99e66a68e0a6fad3f4e19d"`);
        await queryRunner.query(`ALTER TABLE "goalkeeper_profiles" DROP CONSTRAINT "FK_7d3a6f8bb72b65dddef605cbfe1"`);
        await queryRunner.query(`ALTER TABLE "session_exercises" DROP CONSTRAINT "FK_4a44dbff3e955c44d1f6e5d0796"`);
        await queryRunner.query(`ALTER TABLE "session_exercises" DROP CONSTRAINT "FK_834fda65cf08684581b8ae46a74"`);
        await queryRunner.query(`ALTER TABLE "session_exercises" DROP CONSTRAINT "FK_ac33458407f217148bebb9d5d32"`);
        await queryRunner.query(`ALTER TABLE "session_exercises" DROP CONSTRAINT "FK_adb01913c15e1236a8162d7402a"`);
        await queryRunner.query(`ALTER TABLE "session_contents" DROP CONSTRAINT "FK_aa9929921831b3c67fa462069c3"`);
        await queryRunner.query(`ALTER TABLE "session_contents" DROP CONSTRAINT "FK_d43e9d6405dc0909e7da4047b56"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_89e03331414acea30470b8552fd"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_70e7e807de7b0f97a6053343bc9"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_0c5fe8e5f9f4dd4a8c0134abc9c"`);
        await queryRunner.query(`ALTER TABLE "training_contents" DROP CONSTRAINT "FK_f88c40ed2328c7aba3afff8ffd5"`);
        await queryRunner.query(`ALTER TABLE "training_contents" DROP CONSTRAINT "FK_24098a50e31457db8864073cf4a"`);
        await queryRunner.query(`ALTER TABLE "training_contents" DROP CONSTRAINT "FK_f87d75feb9e02b9c11f7ca7b4af"`);
        await queryRunner.query(`ALTER TABLE "training_lines" DROP CONSTRAINT "FK_878e1351989f4a7b8ff96463b8d"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" DROP CONSTRAINT "FK_0cc76cb9b353d25e6521f747fd3"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" DROP CONSTRAINT "FK_9ff1ffdf267ca7e1a05761e967d"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_3d79526cc468e2156893fdb523a"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_e70292ca0e2e6126aa4f09a42d5"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_c58f7e88c286e5e3478960a998b"`);
        await queryRunner.query(`DROP TABLE "auth_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a09e89678290f14d7008d69018"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6eb339774bf35477359d197a20"`);
        await queryRunner.query(`DROP TABLE "email_action_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."email_action_tokens_type_enum"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "evaluations"`);
        await queryRunner.query(`DROP TABLE "evaluation_items"`);
        await queryRunner.query(`DROP TABLE "goalkeeper_profiles"`);
        await queryRunner.query(`DROP TABLE "session_exercises"`);
        await queryRunner.query(`DROP TABLE "session_contents"`);
        await queryRunner.query(`DROP TABLE "exercises"`);
        await queryRunner.query(`DROP TABLE "plan_change_requests"`);
        await queryRunner.query(`DROP TYPE "public"."plan_change_requests_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."plan_change_requests_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."plan_change_requests_requestedplan_enum"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_plan_enum"`);
        await queryRunner.query(`DROP TABLE "training_contents"`);
        await queryRunner.query(`DROP TABLE "training_lines"`);
        await queryRunner.query(`DROP TABLE "training_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."training_sessions_status_enum"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tenants_plan_enum"`);
    }

}
